hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task:
    - env.env_name=PointmassMedium-v0
    - alg.use_rnd=true
    - alg.num_exploration_steps=5000
    - +alg.offline_exploitation=true
    - +alg.cql_alpha=0.5
    - alg.unsupervised_exploration=true
    - env.exp_name=q2_alpha_cql_alpha_0.5
  job:
    name: run_hw8_offrl
    override_dirname: +alg.cql_alpha=0.5,+alg.offline_exploitation=true,alg.num_exploration_steps=5000,alg.unsupervised_exploration=true,alg.use_rnd=true,env.env_name=PointmassMedium-v0,env.exp_name=q2_alpha_cql_alpha_0.5
    id: ???
    num: ???
    config_name: config_hw8
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.1
    cwd: /teamspace/studios/this_studio/robot_learning_2025
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /teamspace/studios/this_studio/robot_learning_2025/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
env:
  env_name: PointmassMedium-v0
  max_episode_length: 200
  exp_name: q2_alpha_cql_alpha_0.5
  atari: false
alg:
  double_q: false
  batch_size: 64
  train_batch_size: 64
  eval_batch_size: 4096
  num_agent_train_steps_per_iter: 2
  num_critic_updates_per_agent_update: 2
  no_gpu: false
  which_gpu: 0
  rl_alg: dqn
  use_rnd: true
  num_exploration_steps: 5000
  unsupervised_exploration: true
  learning_starts: 10000
  learning_freq: 1
  target_update_freq: 10000
  exploration_schedule: 0
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.01
  exploration_decay_steps: 1000000.0
  replay_buffer_size: 1000000
  frame_history_len: 4
  gamma: 0.99
  optimizer_spec:
    constructor: Adam
    optim_kwargs:
      lr: 0.001
      eps: 0.0001
    learning_rate_schedule: 'lambda t: 1.0'
  critic_learning_rate: 0.001
  learning_rate: 0.0001
  ob_dim: 0
  ac_dim: 0
  batch_size_initial: 0
  discrete: true
  grad_norm_clipping: true
  n_iter: 10000
  polyak_avg: 0.01
  td3_target_policy_noise: 0.05
  td3_target_policy_noise_clip: 0.1
  entropy_coeff: 0.2
  policy_std: 0.1
  nn_baseline: false
  deterministic: true
  network:
    layer_sizes:
    - 64
    - 64
    activations:
    - tanh
    - tanh
    output_activation: identity
  offline_exploitation: true
  cql_alpha: 0.5
logging:
  video_log_freq: -1
  scalar_log_freq: 10000
  save_params: false
  random_seed: 1234
  logdir: ''
  debug: false
